# ML-07 — Baseline Action Score and Top-20 Review

**Lane:** Refresh / Content Opportunity Scoring  
**Lane status:** Confirmed and locked  
**Unit of analysis:** One anonymised content page for one anonymised client  
**Development month:** March 2026  
**Feature window:** March 1–15, 2026  
**Outcome window:** March 16–31, 2026 — evaluation only  
**Primary metric:** Precision@50  
**Output:** Ranked human-review queue

This notebook builds the transparent rule-based baseline that the Week-5 model must beat.

It completes the required sections:

1. two signal checks, the rule, and its reason code;
2. the ranked queue and CSV export;
3. a skeptical top-20 review;
4. weak picks and leakage checks;
5. an executable self-check.

The score uses only feature-window information. Outcome-window measurements are used only to evaluate the baseline.

In [1]:
%pip install -q duckdb huggingface_hub pandas numpy scikit-learn

In [3]:
from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path
from typing import Any

import duckdb
import numpy as np
import pandas as pd

from google.colab import userdata
from huggingface_hub import whoami
from sklearn.model_selection import GroupShuffleSplit


# ============================================================
# REPRODUCIBILITY
# ============================================================

SEED = 42
TEST_SIZE = 0.25
TOP_K = 50
TOP_REVIEW_N = 20
MIN_BUCKET_N = 50
DIRECTIONAL_FLOOR = 0.03

np.random.seed(SEED)


# ============================================================
# TIME WINDOWS
# ============================================================

FEATURE_START = "2026-03-01"
FEATURE_END = "2026-03-15"

OUTCOME_START = "2026-03-16"
OUTCOME_END = "2026-03-31"


# ============================================================
# BASELINE POLICY
# ============================================================

MIN_IMPRESSIONS = 500
MIN_FEATURE_DAYS = 5
MIN_POSITION = 0.0
MAX_POSITION = 20.0

CTR_WEAKNESS_WEIGHT = 0.70
VISIBILITY_WEIGHT = 0.30

REASON_CODE = "visible_below_expected_ctr"
ACTION_LABEL = "review_title_meta_and_intent"


# ============================================================
# REPOSITORY
# ============================================================

REPO_URL = "https://github.com/Zafar488/flyrank-ml-internship"
REPO_ROOT = Path("/content/flyrank-ml-internship")

if Path.cwd().name == "flyrank-ml-internship":
    REPO_ROOT = Path.cwd()

elif not REPO_ROOT.exists():
    print("Repository not found. Cloning repository...")

    subprocess.run(
        [
            "git",
            "clone",
            "--depth",
            "1",
            REPO_URL,
            str(REPO_ROOT),
        ],
        check=True,
    )

os.chdir(REPO_ROOT)


# ============================================================
# OUTPUTS
# ============================================================

OUTPUT_DIR = Path("work/outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

QUEUE_PATH = OUTPUT_DIR / "baseline_action_score.csv"
METRICS_PATH = OUTPUT_DIR / "baseline_metrics.json"


# ============================================================
# HUGGING FACE AUTHENTICATION
# ============================================================

HF_TOKEN = userdata.get("HF_TOKEN")

if not HF_TOKEN:
    raise ValueError(
        "HF_TOKEN was not found. Add a Hugging Face Read token "
        "to Colab Secrets and enable notebook access."
    )

user_info = whoami(token=HF_TOKEN)

print(
    "Hugging Face login successful:",
    user_info.get("name", "authenticated-user"),
)


# ============================================================
# DUCKDB
# ============================================================

con = duckdb.connect()

safe_token = HF_TOKEN.replace("'", "''")

con.execute(
    f"""
    CREATE OR REPLACE SECRET hf (
        TYPE huggingface,
        TOKEN '{safe_token}'
    )
    """
)

WAREHOUSE_ROOT = "hf://datasets/FlyRank/internship-warehouse"

MARCH_FACT = (
    "read_parquet("
    f"'{WAREHOUSE_ROOT}/fact_content_daily_performance/"
    "month=2026-03/*.parquet'"
    ")"
)

print("Repository root:", Path.cwd())
print("Feature window:", FEATURE_START, "to", FEATURE_END)
print("Outcome window:", OUTCOME_START, "to", OUTCOME_END)
print("Queue path:", QUEUE_PATH)
print("Metrics path:", METRICS_PATH)

Hugging Face login successful: zafar4050
Repository root: /content/flyrank-ml-internship
Feature window: 2026-03-01 to 2026-03-15
Outcome window: 2026-03-16 to 2026-03-31
Queue path: work/outputs/baseline_action_score.csv
Metrics path: work/outputs/baseline_metrics.json

## Baseline Data Frame

The warehouse source has one row per report date, anonymised client, and anonymised content page.

Daily records are aggregated into one page-level row.

Feature-window fields are used for:

- eligibility;
- signal checks;
- score components;
- reason codes;
- action labels;
- confidence notes;
- the ranked queue.

Outcome-window values are used only to construct the audit proxy and evaluate the baseline. They are not included in the exported queue.

In [4]:
page_frame = con.sql(
    f"""
    SELECT
        client_hash_id,
        content_hash_id,

        SUM(
            CASE
                WHEN report_date BETWEEN
                     DATE '{FEATURE_START}'
                     AND DATE '{FEATURE_END}'
                 AND gsc_data_available IS TRUE
                THEN COALESCE(gsc_impressions, 0)
                ELSE 0
            END
        ) AS feature_impressions,

        SUM(
            CASE
                WHEN report_date BETWEEN
                     DATE '{FEATURE_START}'
                     AND DATE '{FEATURE_END}'
                 AND gsc_data_available IS TRUE
                THEN COALESCE(gsc_clicks, 0)
                ELSE 0
            END
        ) AS feature_clicks,

        AVG(
            CASE
                WHEN report_date BETWEEN
                     DATE '{FEATURE_START}'
                     AND DATE '{FEATURE_END}'
                 AND gsc_data_available IS TRUE
                THEN gsc_avg_position
            END
        ) AS feature_avg_position,

        STDDEV_SAMP(
            CASE
                WHEN report_date BETWEEN
                     DATE '{FEATURE_START}'
                     AND DATE '{FEATURE_END}'
                 AND gsc_data_available IS TRUE
                THEN gsc_avg_position
            END
        ) AS feature_position_volatility,

        COUNT(
            DISTINCT CASE
                WHEN report_date BETWEEN
                     DATE '{FEATURE_START}'
                     AND DATE '{FEATURE_END}'
                 AND gsc_data_available IS TRUE
                THEN report_date
            END
        ) AS feature_available_days,

        SUM(
            CASE
                WHEN report_date BETWEEN
                     DATE '{OUTCOME_START}'
                     AND DATE '{OUTCOME_END}'
                 AND gsc_data_available IS TRUE
                THEN COALESCE(gsc_impressions, 0)
                ELSE 0
            END
        ) AS outcome_impressions,

        COUNT(
            DISTINCT CASE
                WHEN report_date BETWEEN
                     DATE '{OUTCOME_START}'
                     AND DATE '{OUTCOME_END}'
                 AND gsc_data_available IS TRUE
                THEN report_date
            END
        ) AS outcome_available_days

    FROM {MARCH_FACT}

    GROUP BY
        client_hash_id,
        content_hash_id
    """
).df()

duplicate_rows = int(
    page_frame.duplicated(
        subset=[
            "client_hash_id",
            "content_hash_id",
        ]
    ).sum()
)

print("Raw client-page rows:", f"{len(page_frame):,}")
print("Duplicate client-page rows:", duplicate_rows)

assert duplicate_rows == 0


# ============================================================
# FEATURE-WINDOW DERIVATIVES
# ============================================================

page_frame["feature_ctr"] = np.where(
    page_frame["feature_impressions"] > 0,
    (
        page_frame["feature_clicks"]
        / page_frame["feature_impressions"]
    ),
    np.nan,
)

volatility_fill = page_frame[
    "feature_position_volatility"
].median()

if pd.isna(volatility_fill):
    volatility_fill = 0.0

page_frame["feature_position_volatility"] = (
    page_frame["feature_position_volatility"]
    .fillna(float(volatility_fill))
)

page_frame["position_band"] = pd.cut(
    page_frame["feature_avg_position"],
    bins=[
        0,
        3,
        10,
        20,
    ],
    labels=[
        "Top 3",
        "Page 1",
        "Page 2",
    ],
    include_lowest=True,
)

page_frame["position_band"] = (
    page_frame["position_band"]
    .astype("object")
)


# ============================================================
# AUDIT-ONLY FRAME
# ============================================================

audit_frame = page_frame[
    (page_frame["feature_impressions"] >= 100)
    & (page_frame["feature_available_days"] >= MIN_FEATURE_DAYS)
    & (page_frame["outcome_available_days"] >= 5)
].copy()

audit_frame["feature_daily_impressions"] = np.where(
    audit_frame["feature_available_days"] > 0,
    (
        audit_frame["feature_impressions"]
        / audit_frame["feature_available_days"]
    ),
    np.nan,
)

audit_frame["outcome_daily_impressions"] = np.where(
    audit_frame["outcome_available_days"] > 0,
    (
        audit_frame["outcome_impressions"]
        / audit_frame["outcome_available_days"]
    ),
    np.nan,
)

audit_frame["is_declining_proxy"] = (
    audit_frame["outcome_daily_impressions"]
    < 0.80 * audit_frame["feature_daily_impressions"]
).astype(int)


# ============================================================
# FEATURE-ONLY OPERATIONAL FRAME
# ============================================================

baseline_feature_columns = [
    "client_hash_id",
    "content_hash_id",
    "feature_impressions",
    "feature_clicks",
    "feature_ctr",
    "feature_avg_position",
    "feature_position_volatility",
    "feature_available_days",
    "position_band",
]

baseline_mask = (
    (page_frame["feature_impressions"] >= MIN_IMPRESSIONS)
    & (page_frame["feature_available_days"] >= MIN_FEATURE_DAYS)
    & (page_frame["feature_avg_position"] > MIN_POSITION)
    & (page_frame["feature_avg_position"] <= MAX_POSITION)
    & (page_frame["feature_ctr"].notna())
    & (page_frame["position_band"].notna())
)

baseline_frame = (
    page_frame.loc[
        baseline_mask,
        baseline_feature_columns,
    ]
    .copy()
    .drop_duplicates(
        subset=[
            "client_hash_id",
            "content_hash_id",
        ]
    )
    .reset_index(drop=True)
)

print("Audit rows:", f"{len(audit_frame):,}")
print(
    "Audit declining-proxy rate:",
    round(audit_frame["is_declining_proxy"].mean(), 3),
)
print(
    "Feature-only operational rows:",
    f"{len(baseline_frame):,}",
)
print(
    "Anonymised clients:",
    baseline_frame["client_hash_id"].nunique(),
)

assert len(baseline_frame) > TOP_REVIEW_N
assert "outcome_impressions" not in baseline_frame.columns
assert "is_declining_proxy" not in baseline_frame.columns

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Raw client-page rows: 331,437
Duplicate client-page rows: 0
Audit rows: 76,201
Audit declining-proxy rate: 0.345
Feature-only operational rows: 34,078
Anonymised clients: 32

## 1. My Rule and Its Reason Code

The rule uses two signals.

### Signal 1 — CTR Relative to Position

This signal is linked to FlyRank's CTR-review logic.

A page is compared with the median CTR of pages in the same position band because CTR opportunity changes with search rank.

### Signal 2 — Visibility / Impressions

Visibility represents potential business impact.

It is not treated as proof that a page requires editing.

Each table includes `n` and receives one verdict:

**CONFIRMED / OPPOSITE / MIXED / FALSE**

In [5]:
# ============================================================
# SIGNAL 1 — CTR RELATIVE TO POSITION
# ============================================================

ctr_signal_frame = audit_frame[
    (audit_frame["feature_impressions"] >= MIN_IMPRESSIONS)
    & (audit_frame["feature_avg_position"] > MIN_POSITION)
    & (audit_frame["feature_avg_position"] <= MAX_POSITION)
    & (audit_frame["feature_ctr"].notna())
    & (audit_frame["position_band"].notna())
].copy()

ctr_reference = (
    ctr_signal_frame
    .groupby(
        "position_band",
        observed=True,
    )["feature_ctr"]
    .median()
    .rename("expected_ctr_for_band")
)

ctr_signal_frame = ctr_signal_frame.merge(
    ctr_reference,
    left_on="position_band",
    right_index=True,
    how="left",
)

ctr_signal_frame["ctr_gap"] = (
    ctr_signal_frame["feature_ctr"]
    - ctr_signal_frame["expected_ctr_for_band"]
)

ctr_signal_frame["ctr_status"] = np.where(
    ctr_signal_frame["ctr_gap"] < 0,
    "Below band median",
    "At or above band median",
)

signal_1_table = (
    ctr_signal_frame
    .groupby(
        [
            "position_band",
            "ctr_status",
        ],
        observed=True,
    )
    .agg(
        n=(
            "is_declining_proxy",
            "size",
        ),
        declining_pages=(
            "is_declining_proxy",
            "sum",
        ),
        decline_rate=(
            "is_declining_proxy",
            "mean",
        ),
        median_impressions=(
            "feature_impressions",
            "median",
        ),
        median_ctr=(
            "feature_ctr",
            "median",
        ),
        median_ctr_gap=(
            "ctr_gap",
            "median",
        ),
    )
    .reset_index()
)

signal_1_table["decline_rate_pct"] = (
    100 * signal_1_table["decline_rate"]
)

display(signal_1_table.round(4))

signal_1_summary = (
    ctr_signal_frame
    .groupby(
        "ctr_status",
        observed=True,
    )
    .agg(
        n=(
            "is_declining_proxy",
            "size",
        ),
        decline_rate=(
            "is_declining_proxy",
            "mean",
        ),
    )
    .reset_index()
)

signal_1_rate_map = dict(
    zip(
        signal_1_summary["ctr_status"],
        signal_1_summary["decline_rate"],
    )
)

below_ctr_rate = float(
    signal_1_rate_map["Below band median"]
)

above_ctr_rate = float(
    signal_1_rate_map["At or above band median"]
)

signal_1_difference = (
    below_ctr_rate
    - above_ctr_rate
)

if signal_1_summary["n"].min() < MIN_BUCKET_N:
    signal_1_verdict = "FALSE"

elif signal_1_difference >= DIRECTIONAL_FLOOR:
    signal_1_verdict = "CONFIRMED"

elif signal_1_difference <= -DIRECTIONAL_FLOOR:
    signal_1_verdict = "OPPOSITE"

else:
    signal_1_verdict = "MIXED"

print("Signal 1 — CTR relative to position")
print("Verdict:", signal_1_verdict)
print(
    "Below-minus-above decline-rate difference:",
    round(signal_1_difference, 3),
)


# ============================================================
# SIGNAL 2 — VISIBILITY / IMPRESSIONS
# ============================================================

audit_frame["visibility_bucket"] = pd.cut(
    audit_frame["feature_impressions"],
    bins=[
        99,
        499,
        1_999,
        9_999,
        np.inf,
    ],
    labels=[
        "100-499",
        "500-1,999",
        "2,000-9,999",
        "10,000+",
    ],
    include_lowest=True,
)

signal_2_table = (
    audit_frame
    .groupby(
        "visibility_bucket",
        observed=True,
    )
    .agg(
        n=(
            "is_declining_proxy",
            "size",
        ),
        declining_pages=(
            "is_declining_proxy",
            "sum",
        ),
        decline_rate=(
            "is_declining_proxy",
            "mean",
        ),
        median_impressions=(
            "feature_impressions",
            "median",
        ),
    )
    .reset_index()
)

signal_2_table["decline_rate_pct"] = (
    100 * signal_2_table["decline_rate"]
)

display(signal_2_table.round(4))

visibility_rates = (
    signal_2_table["decline_rate"]
    .dropna()
    .to_numpy()
)

visibility_counts = (
    signal_2_table["n"]
    .to_numpy()
)

visibility_range = float(
    visibility_rates.max()
    - visibility_rates.min()
)

if (
    len(visibility_rates) < 2
    or np.any(visibility_counts < MIN_BUCKET_N)
):
    signal_2_verdict = "FALSE"

elif visibility_range < DIRECTIONAL_FLOOR:
    signal_2_verdict = "FALSE"

elif np.all(np.diff(visibility_rates) >= 0):
    signal_2_verdict = "CONFIRMED"

elif np.all(np.diff(visibility_rates) <= 0):
    signal_2_verdict = "OPPOSITE"

else:
    signal_2_verdict = "MIXED"

print("Signal 2 — Visibility / impressions")
print("Verdict:", signal_2_verdict)
print(
    "Decline-rate range:",
    round(visibility_range, 3),
)


signal_verdicts = pd.DataFrame(
    [
        {
            "signal": "CTR relative to position",
            "flag_linked": True,
            "verdict": signal_1_verdict,
            "baseline_role": "Primary weakness signal",
        },
        {
            "signal": "Visibility / impressions",
            "flag_linked": False,
            "verdict": signal_2_verdict,
            "baseline_role": "Impact weight only",
        },
    ]
)

display(signal_verdicts)

,position_band,ctr_status,n,declining_pages,decline_rate,median_impressions,median_ctr,median_ctr_gap,decline_rate_pct
0,Page 1,At or above band median,10489,2512,0.2395,1469.0,0.0044,0.0023,23.9489
1,Page 1,Below band median,10488,4389,0.4185,1310.0,0.0009,-0.0012,41.8478
2,Page 2,At or above band median,3413,657,0.1925,947.0,0.0047,0.0022,19.2499
3,Page 2,Below band median,3411,1224,0.3588,998.0,0.0008,-0.0017,35.8839
4,Top 3,At or above band median,3119,577,0.1850,1690.0,0.0058,0.0028,18.4995
5,Top 3,Below band median,3118,1158,0.3714,1550.5,0.0014,-0.0016,37.1392

Signal 1 — CTR relative to position
Verdict: CONFIRMED
Below-minus-above decline-rate difference: 0.178

,visibility_bucket,n,declining_pages,decline_rate,median_impressions,decline_rate_pct
0,100-499,34590,12062,0.3487,224.0,34.8714
1,"500-1,999",26261,8784,0.3345,922.0,33.4488
2,"2,000-9,999",13474,4670,0.3466,3443.5,34.6593
3,"10,000+",1876,748,0.3987,14786.5,39.8721

Signal 2 — Visibility / impressions
Verdict: MIXED
Decline-rate range: 0.064

                     signal  flag_linked    verdict            baseline_role
0  CTR relative to position         True  CONFIRMED  Primary weakness signal
1  Visibility / impressions        False      MIXED       Impact weight only

### Signal Interpretation

CTR relative to position is the primary weakness signal.

A confirmed result means pages below their position-band CTR reference showed a higher observed later decline rate.

Visibility has a mixed relationship with the proxy. It is therefore used only as an impact weight.

### Rule in Plain Words

A page enters the queue when:

1. it has at least 500 feature-window impressions;
2. it has at least five available feature-window days;
3. its average position is greater than 0 and no more than 20;
4. its CTR is below the median CTR of pages in the same position band.

The score uses fixed hand-written weights:

- **70% position-adjusted CTR weakness**
- **30% visibility percentile**

### One Reason Code

`visible_below_expected_ctr`

### One Action Label

`review_title_meta_and_intent`

The action asks a human editor to review the title, metadata, search intent, snippet relevance, and page-content alignment before making any change.

## 2. Build the Ranked Queue

The score is evaluated on a grouped-client holdout.

The grouped reference rows define:

- the median CTR for each position band;
- the visibility percentile reference distribution.

The weights and rule remain fixed and hand-written.

In [6]:
def empirical_percentile(
    values: Any,
    reference_values: Any,
) -> np.ndarray:
    values_array = np.asarray(
        values,
        dtype=float,
    )

    reference_array = np.sort(
        np.asarray(
            reference_values,
            dtype=float,
        )
    )

    reference_array = reference_array[
        np.isfinite(reference_array)
    ]

    if len(reference_array) == 0:
        raise ValueError(
            "Reference distribution cannot be empty."
        )

    return (
        np.searchsorted(
            reference_array,
            values_array,
            side="right",
        )
        / len(reference_array)
    )


def build_baseline_scores(
    scoring_frame: pd.DataFrame,
    reference_frame: pd.DataFrame,
) -> pd.DataFrame:
    output = scoring_frame.copy()

    reference_with_key = reference_frame.copy()

    reference_with_key["position_band_key"] = (
        reference_with_key["position_band"]
        .astype(str)
    )

    reference_ctr_by_band = (
        reference_with_key
        .groupby(
            "position_band_key",
            observed=True,
        )["feature_ctr"]
        .median()
        .to_dict()
    )

    global_reference_ctr = float(
        reference_frame["feature_ctr"].median()
    )

    output["expected_ctr_for_band"] = (
        output["position_band"]
        .astype(str)
        .map(reference_ctr_by_band)
        .astype(float)
        .fillna(global_reference_ctr)
    )

    output["ctr_gap"] = (
        output["feature_ctr"]
        - output["expected_ctr_for_band"]
    )

    output["ctr_weakness_score"] = np.where(
        output["expected_ctr_for_band"] > 0,
        (
            -output["ctr_gap"]
            / output["expected_ctr_for_band"]
        ),
        0.0,
    )

    output["ctr_weakness_score"] = (
        output["ctr_weakness_score"]
        .clip(
            lower=0.0,
            upper=1.0,
        )
    )

    output["visibility_percentile"] = empirical_percentile(
        output["feature_impressions"],
        reference_frame["feature_impressions"],
    )

    output["baseline_eligible"] = (
        output["ctr_gap"] < 0
    )

    output["baseline_action_score"] = (
        100
        * (
            CTR_WEAKNESS_WEIGHT
            * output["ctr_weakness_score"]
            +
            VISIBILITY_WEIGHT
            * output["visibility_percentile"]
        )
    ).round(4)

    output.loc[
        ~output["baseline_eligible"],
        "baseline_action_score",
    ] = 0.0

    output["reason_code"] = np.where(
        output["baseline_eligible"],
        REASON_CODE,
        "",
    )

    output["action_label"] = np.where(
        output["baseline_eligible"],
        ACTION_LABEL,
        "no_immediate_action",
    )

    output["confidence_note"] = np.select(
        [
            (
                output["ctr_weakness_score"] >= 0.75
            )
            & (
                output["visibility_percentile"] >= 0.75
            ),
            (
                output["ctr_weakness_score"] >= 0.50
            )
            & (
                output["visibility_percentile"] >= 0.50
            ),
        ],
        [
            "higher-confidence review candidate",
            "medium-confidence review candidate",
        ],
        default="lower-confidence review candidate",
    )

    return output


def precision_at_k(
    scores: Any,
    labels: Any,
    k: int,
) -> float:
    score_array = np.asarray(
        scores,
        dtype=float,
    )

    label_array = np.asarray(
        labels,
        dtype=int,
    )

    if len(score_array) != len(label_array):
        raise ValueError(
            "Scores and labels must have equal length."
        )

    if not np.isfinite(score_array).all():
        raise ValueError(
            "Scores contain NaN or infinite values."
        )

    effective_k = min(
        k,
        len(label_array),
    )

    ranked_indices = np.argsort(
        -score_array,
        kind="mergesort",
    )[:effective_k]

    return float(
        label_array[ranked_indices].mean()
    )


# ============================================================
# GROUPED EVALUATION
# ============================================================

evaluation_mask = (
    (audit_frame["feature_impressions"] >= MIN_IMPRESSIONS)
    & (audit_frame["feature_available_days"] >= MIN_FEATURE_DAYS)
    & (audit_frame["feature_avg_position"] > MIN_POSITION)
    & (audit_frame["feature_avg_position"] <= MAX_POSITION)
    & (audit_frame["feature_ctr"].notna())
    & (audit_frame["position_band"].notna())
)

evaluation_frame = (
    audit_frame.loc[
        evaluation_mask,
        [
            *baseline_feature_columns,
            "is_declining_proxy",
        ],
    ]
    .copy()
    .drop_duplicates(
        subset=[
            "client_hash_id",
            "content_hash_id",
        ]
    )
    .reset_index(drop=True)
)

splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=TEST_SIZE,
    random_state=SEED,
)

reference_index, validation_index = next(
    splitter.split(
        evaluation_frame,
        evaluation_frame["is_declining_proxy"],
        groups=evaluation_frame["client_hash_id"],
    )
)

reference_frame = (
    evaluation_frame
    .iloc[reference_index]
    .copy()
    .reset_index(drop=True)
)

validation_frame = (
    evaluation_frame
    .iloc[validation_index]
    .copy()
    .reset_index(drop=True)
)

reference_clients = set(
    reference_frame["client_hash_id"].unique()
)

validation_clients = set(
    validation_frame["client_hash_id"].unique()
)

client_overlap = len(
    reference_clients.intersection(
        validation_clients
    )
)

assert client_overlap == 0

validation_scored = build_baseline_scores(
    scoring_frame=validation_frame,
    reference_frame=reference_frame,
)

validation_labels = (
    validation_scored["is_declining_proxy"]
    .to_numpy(dtype=int)
)

validation_scores = (
    validation_scored["baseline_action_score"]
    .to_numpy(dtype=float)
)

validation_base_rate = float(
    validation_labels.mean()
)

baseline_precision_at_50 = precision_at_k(
    validation_scores,
    validation_labels,
    TOP_K,
)

top_50_positive_count = int(
    round(
        baseline_precision_at_50
        * min(
            TOP_K,
            len(validation_labels),
        )
    )
)

precision_lift_vs_base_rate = (
    baseline_precision_at_50
    - validation_base_rate
)

print("GROUPED BASELINE EVALUATION")
print("-" * 60)
print("Reference rows:", f"{len(reference_frame):,}")
print("Validation rows:", f"{len(validation_frame):,}")
print("Reference clients:", len(reference_clients))
print("Validation clients:", len(validation_clients))
print("Client overlap:", client_overlap)
print(
    "Validation positive base rate:",
    round(validation_base_rate, 3),
)
print(
    "Baseline Precision@50:",
    round(baseline_precision_at_50, 3),
)
print(
    "Top-50 declining-proxy pages:",
    top_50_positive_count,
)
print(
    "Precision@50 minus base rate:",
    round(precision_lift_vs_base_rate, 3),
)


# ============================================================
# FULL FEATURE-ONLY QUEUE
# ============================================================

full_scored_frame = build_baseline_scores(
    scoring_frame=baseline_frame,
    reference_frame=baseline_frame,
)

baseline_queue = (
    full_scored_frame[
        full_scored_frame["baseline_eligible"]
    ]
    .copy()
    .sort_values(
        [
            "baseline_action_score",
            "ctr_weakness_score",
            "feature_impressions",
        ],
        ascending=[
            False,
            False,
            False,
        ],
        kind="mergesort",
    )
    .reset_index(drop=True)
)

baseline_queue.insert(
    0,
    "rank",
    np.arange(
        1,
        len(baseline_queue) + 1,
    ),
)

queue_columns = [
    "rank",
    "client_hash_id",
    "content_hash_id",
    "baseline_action_score",
    "reason_code",
    "action_label",
    "confidence_note",
    "feature_impressions",
    "feature_clicks",
    "feature_ctr",
    "feature_avg_position",
    "feature_position_volatility",
    "feature_available_days",
    "position_band",
    "expected_ctr_for_band",
    "ctr_gap",
    "ctr_weakness_score",
    "visibility_percentile",
]

ranked_queue = (
    baseline_queue[
        queue_columns
    ]
    .copy()
)

ranked_queue.to_csv(
    QUEUE_PATH,
    index=False,
)

public_queue_columns = [
    "rank",
    "baseline_action_score",
    "reason_code",
    "action_label",
    "confidence_note",
    "feature_impressions",
    "feature_ctr",
    "feature_avg_position",
    "position_band",
    "expected_ctr_for_band",
    "ctr_gap",
    "ctr_weakness_score",
    "visibility_percentile",
]

print("Ranked queue rows:", f"{len(ranked_queue):,}")
print("Saved:", QUEUE_PATH)

display(
    ranked_queue[
        public_queue_columns
    ]
    .head(TOP_REVIEW_N)
    .round(5)
)

GROUPED BASELINE EVALUATION
------------------------------------------------------------
Reference rows: 18,075
Validation rows: 15,963
Reference clients: 24
Validation clients: 8
Client overlap: 0
Validation positive base rate: 0.301
Baseline Precision@50: 0.52
Top-50 declining-proxy pages: 26
Precision@50 minus base rate: 0.219
Ranked queue rows: 17,038
Saved: work/outputs/baseline_action_score.csv

,rank,baseline_action_score,reason_code,action_label,confidence_note,feature_impressions,feature_ctr,feature_avg_position,position_band,expected_ctr_for_band,ctr_gap,ctr_weakness_score,visibility_percentile
0,1,99.9938,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,83772.0,0.00000,8.60791,Page 1,0.00211,-0.00211,1.00000,0.99979
1,2,99.8829,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,27715.0,0.00000,5.35782,Page 1,0.00211,-0.00211,1.00000,0.99610
2,3,99.6699,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,18554.0,0.00000,3.39174,Page 1,0.00211,-0.00211,1.00000,0.98900
3,4,99.6664,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,18421.0,0.00000,5.21686,Page 1,0.00211,-0.00211,1.00000,0.98888
4,5,99.6241,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,17150.0,0.00000,8.16091,Page 1,0.00211,-0.00211,1.00000,0.98747
5,6,99.5871,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,16711.0,0.00000,8.73714,Page 1,0.00211,-0.00211,1.00000,0.98624
6,7,99.4797,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,15012.0,0.00000,3.88750,Page 1,0.00211,-0.00211,1.00000,0.98266
7,8,99.4180,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,58553.0,0.00002,4.57905,Page 1,0.00211,-0.00210,0.99192,0.99944
8,9,99.3644,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,13576.0,0.00000,6.40399,Page 1,0.00211,-0.00211,1.00000,0.97881
9,10,99.2711,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,12634.0,0.00000,16.67551,Page 2,0.00251,-0.00251,1.00000,0.97570
10,11,99.1945,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,12020.0,0.00000,8.45368,Page 1,0.00211,-0.00211,1.00000,0.97315
11,12,99.1663,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,11830.0,0.00000,7.27843,Page 1,0.00211,-0.00211,1.00000,0.97221
12,13,99.1179,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,11457.0,0.00000,2.72685,Top 3,0.00301,-0.00301,1.00000,0.97060
13,14,98.7614,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,9498.0,0.00000,13.69364,Page 2,0.00251,-0.00251,1.00000,0.95871
14,15,98.7191,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,9307.0,0.00000,3.59674,Page 1,0.00211,-0.00211,1.00000,0.95730
15,16,98.6277,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,49314.0,0.00004,6.41378,Page 1,0.00211,-0.00207,0.98082,0.99900
16,17,98.6196,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,8895.0,0.00000,7.34368,Page 1,0.00211,-0.00211,1.00000,0.95399
17,18,98.5228,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,8569.0,0.00000,1.43066,Top 3,0.00301,-0.00301,1.00000,0.95076
18,19,98.5175,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,8560.0,0.00000,4.20300,Page 1,0.00211,-0.00211,1.00000,0.95058
19,20,98.4621,visible_below_expected_ctr,review_title_meta_and_intent,higher-confidence review candidate,8370.0,0.00000,9.78614,Page 1,0.00211,-0.00211,1.00000,0.94874

## 3. Top-20 Review

Each of the top 20 includes:

- action;
- reason code;
- confidence note;
- why it appears;
- what would make the recommendation wrong.

The displayed review excludes client and content identifiers.

In [7]:
top_20_review = (
    ranked_queue
    .head(TOP_REVIEW_N)
    .copy()
)

top_20_review["why_it_is_here"] = top_20_review.apply(
    lambda row: (
        f"CTR {row['feature_ctr']:.4f} is below the "
        f"{row['position_band']} reference "
        f"{row['expected_ctr_for_band']:.4f}; "
        f"the page had {int(row['feature_impressions']):,} "
        "feature-window impressions."
    ),
    axis=1,
)

volatility_p90 = float(
    ranked_queue[
        "feature_position_volatility"
    ].quantile(0.90)
)


def build_wrong_reason(
    row: pd.Series,
) -> str:
    position = float(
        row["feature_avg_position"]
    )

    impressions = int(
        row["feature_impressions"]
    )

    ctr_gap = float(
        row["ctr_gap"]
    )

    volatility = float(
        row["feature_position_volatility"]
    )

    if position <= 3:
        return (
            "The page may serve navigational or low-click SERP intent, "
            "so low CTR may be normal despite a Top-3 position."
        )

    if volatility >= volatility_p90:
        return (
            "The feature window may reflect temporary ranking volatility "
            "rather than a stable metadata or intent problem."
        )

    if impressions >= 10_000:
        return (
            "High impressions may come from broad or seasonal queries; "
            "aggregate CTR can be low even when the page is healthy."
        )

    if abs(ctr_gap) < 0.0005:
        return (
            "The measured CTR gap is small and may be noise rather than "
            "a meaningful review signal."
        )

    if position > 10:
        return (
            "Page-2 visibility may be the main constraint; changing the "
            "title or metadata alone may not improve performance."
        )

    return (
        "SERP features, query mix, seasonality, or search intent may "
        "explain the CTR gap without requiring a page change."
    )


top_20_review["what_would_make_it_wrong"] = (
    top_20_review.apply(
        build_wrong_reason,
        axis=1,
    )
)

top_20_review["review_line"] = top_20_review.apply(
    lambda row: (
        f"Rank {int(row['rank'])} | "
        f"Action: {row['action_label']} | "
        f"Reason: {row['reason_code']} | "
        f"Confidence: {row['confidence_note']} | "
        f"Why: {row['why_it_is_here']} | "
        f"Wrong if: {row['what_would_make_it_wrong']}"
    ),
    axis=1,
)

top_20_review_output = top_20_review[
    [
        "rank",
        "baseline_action_score",
        "action_label",
        "reason_code",
        "confidence_note",
        "why_it_is_here",
        "what_would_make_it_wrong",
        "review_line",
    ]
].copy()

display(top_20_review_output)

print("TOP-20 REVIEW LINES")
print("-" * 80)

for review_line in top_20_review_output["review_line"]:
    print(review_line)
    print()

,rank,baseline_action_score,action_label,reason_code,confidence_note,why_it_is_here,what_would_make_it_wrong,review_line
0,1,99.9938,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,The feature window may reflect temporary ranki...,Rank 1 | Action: review_title_meta_and_intent ...
1,2,99.8829,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,High impressions may come from broad or season...,Rank 2 | Action: review_title_meta_and_intent ...
2,3,99.6699,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,High impressions may come from broad or season...,Rank 3 | Action: review_title_meta_and_intent ...
3,4,99.6664,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,High impressions may come from broad or season...,Rank 4 | Action: review_title_meta_and_intent ...
4,5,99.6241,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,High impressions may come from broad or season...,Rank 5 | Action: review_title_meta_and_intent ...
5,6,99.5871,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,High impressions may come from broad or season...,Rank 6 | Action: review_title_meta_and_intent ...
6,7,99.4797,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,High impressions may come from broad or season...,Rank 7 | Action: review_title_meta_and_intent ...
7,8,99.4180,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,High impressions may come from broad or season...,Rank 8 | Action: review_title_meta_and_intent ...
8,9,99.3644,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,High impressions may come from broad or season...,Rank 9 | Action: review_title_meta_and_intent ...
9,10,99.2711,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 2 reference 0.002...,The feature window may reflect temporary ranki...,Rank 10 | Action: review_title_meta_and_intent...
10,11,99.1945,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,The feature window may reflect temporary ranki...,Rank 11 | Action: review_title_meta_and_intent...
11,12,99.1663,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,High impressions may come from broad or season...,Rank 12 | Action: review_title_meta_and_intent...
12,13,99.1179,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Top 3 reference 0.0030...,The page may serve navigational or low-click S...,Rank 13 | Action: review_title_meta_and_intent...
13,14,98.7614,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 2 reference 0.002...,Page-2 visibility may be the main constraint; ...,Rank 14 | Action: review_title_meta_and_intent...
14,15,98.7191,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,"SERP features, query mix, seasonality, or sear...",Rank 15 | Action: review_title_meta_and_intent...
15,16,98.6277,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,High impressions may come from broad or season...,Rank 16 | Action: review_title_meta_and_intent...
16,17,98.6196,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,"SERP features, query mix, seasonality, or sear...",Rank 17 | Action: review_title_meta_and_intent...
17,18,98.5228,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Top 3 reference 0.0030...,The page may serve navigational or low-click S...,Rank 18 | Action: review_title_meta_and_intent...
18,19,98.5175,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,"SERP features, query mix, seasonality, or sear...",Rank 19 | Action: review_title_meta_and_intent...
19,20,98.4621,review_title_meta_and_intent,visible_below_expected_ctr,higher-confidence review candidate,CTR 0.0000 is below the Page 1 reference 0.002...,"SERP features, query mix, seasonality, or sear...",Rank 20 | Action: review_title_meta_and_intent...

TOP-20 REVIEW LINES
--------------------------------------------------------------------------------
Rank 1 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 83,772 feature-window impressions. | Wrong if: The feature window may reflect temporary ranking volatility rather than a stable metadata or intent problem.

Rank 2 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 27,715 feature-window impressions. | Wrong if: High impressions may come from broad or seasonal queries; aggregate CTR can be low even when the page is healthy.

Rank 3 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 18,554 feature-window impressions. | Wrong if: High impressions may come from broad or seasonal queries; aggregate CTR can be low even when the page is healthy.

Rank 4 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 18,421 feature-window impressions. | Wrong if: High impressions may come from broad or seasonal queries; aggregate CTR can be low even when the page is healthy.

Rank 5 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 17,150 feature-window impressions. | Wrong if: High impressions may come from broad or seasonal queries; aggregate CTR can be low even when the page is healthy.

Rank 6 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 16,711 feature-window impressions. | Wrong if: High impressions may come from broad or seasonal queries; aggregate CTR can be low even when the page is healthy.

Rank 7 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 15,012 feature-window impressions. | Wrong if: High impressions may come from broad or seasonal queries; aggregate CTR can be low even when the page is healthy.

Rank 8 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 58,553 feature-window impressions. | Wrong if: High impressions may come from broad or seasonal queries; aggregate CTR can be low even when the page is healthy.

Rank 9 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 13,576 feature-window impressions. | Wrong if: High impressions may come from broad or seasonal queries; aggregate CTR can be low even when the page is healthy.

Rank 10 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 2 reference 0.0025; the page had 12,634 feature-window impressions. | Wrong if: The feature window may reflect temporary ranking volatility rather than a stable metadata or intent problem.

Rank 11 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 12,020 feature-window impressions. | Wrong if: The feature window may reflect temporary ranking volatility rather than a stable metadata or intent problem.

Rank 12 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 11,830 feature-window impressions. | Wrong if: High impressions may come from broad or seasonal queries; aggregate CTR can be low even when the page is healthy.

Rank 13 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Top 3 reference 0.0030; the page had 11,457 feature-window impressions. | Wrong if: The page may serve navigational or low-click SERP intent, so low CTR may be normal despite a Top-3 position.

Rank 14 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 2 reference 0.0025; the page had 9,498 feature-window impressions. | Wrong if: Page-2 visibility may be the main constraint; changing the title or metadata alone may not improve performance.

Rank 15 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 9,307 feature-window impressions. | Wrong if: SERP features, query mix, seasonality, or search intent may explain the CTR gap without requiring a page change.

Rank 16 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 49,314 feature-window impressions. | Wrong if: High impressions may come from broad or seasonal queries; aggregate CTR can be low even when the page is healthy.

Rank 17 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 8,895 feature-window impressions. | Wrong if: SERP features, query mix, seasonality, or search intent may explain the CTR gap without requiring a page change.

Rank 18 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Top 3 reference 0.0030; the page had 8,569 feature-window impressions. | Wrong if: The page may serve navigational or low-click SERP intent, so low CTR may be normal despite a Top-3 position.

Rank 19 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 8,560 feature-window impressions. | Wrong if: SERP features, query mix, seasonality, or search intent may explain the CTR gap without requiring a page change.

Rank 20 | Action: review_title_meta_and_intent | Reason: visible_below_expected_ctr | Confidence: higher-confidence review candidate | Why: CTR 0.0000 is below the Page 1 reference 0.0021; the page had 8,370 feature-window impressions. | Wrong if: SERP features, query mix, seasonality, or search intent may explain the CTR gap without requiring a page change.

## 4. Weak Picks and Leakage Check

Weak picks are the top-20 rows with the smallest combined evidence margin.

This does not prove those pages are wrong. It identifies recommendations that deserve more cautious human review.

The leakage check confirms that future measurements, labels, product flags, names, URLs, and private queries are absent from the score.

In [9]:
# ============================================================
# WEAK PICKS
# ============================================================

top_20_review["evidence_margin"] = (
    top_20_review["ctr_weakness_score"]
    * top_20_review["visibility_percentile"]
)

weak_picks = (
    top_20_review
    .sort_values(
        [
            "evidence_margin",
            "baseline_action_score",
        ],
        ascending=[
            True,
            True,
        ],
    )
    .head(5)
    .copy()
)

weak_picks["weak_pick_reason"] = weak_picks.apply(
    lambda row: (
        f"Rank {int(row['rank'])} is relatively weaker because "
        f"its combined evidence margin is "
        f"{row['evidence_margin']:.4f}. "
        f"{row['what_would_make_it_wrong']}"
    ),
    axis=1,
)

display(
    weak_picks[
        [
            "rank",
            "baseline_action_score",
            "evidence_margin",
            "weak_pick_reason",
        ]
    ].round(5)
)


# ============================================================
# LEAKAGE CHECK
# ============================================================

score_input_columns = {
    "feature_impressions",
    "feature_clicks",
    "feature_ctr",
    "feature_avg_position",
    "feature_position_volatility",
    "feature_available_days",
    "position_band",
    "expected_ctr_for_band",
    "ctr_gap",
    "ctr_weakness_score",
    "visibility_percentile",
}

forbidden_score_inputs = {
    "outcome_impressions",
    "outcome_daily_impressions",
    "outcome_available_days",
    "is_declining_proxy",
    "decline_ratio",
    "trend_direction",
    "trend_pct",
    "health_score",
    "priority_score",
    "action_type",
    "needs_ctr_fix",
    "refresh_flag",
    "client_hash_id",
    "content_hash_id",
}

forbidden_score_overlap = sorted(
    score_input_columns.intersection(
        forbidden_score_inputs
    )
)

forbidden_export_fields = {
    "outcome_impressions",
    "outcome_daily_impressions",
    "outcome_available_days",
    "is_declining_proxy",
    "decline_ratio",
    "trend_direction",
    "trend_pct",
    "health_score",
    "priority_score",
    "needs_ctr_fix",
    "refresh_flag",
}

exported_forbidden_fields = sorted(
    set(ranked_queue.columns).intersection(
        forbidden_export_fields
    )
)

privacy_patterns = [
    "url",
    "domain",
    "raw_query",
    "query_text",
    "client_name",
    "email",
    "token",
]

exported_privacy_risks = sorted(
    column
    for column in ranked_queue.columns
    if any(
        pattern in column.lower()
        for pattern in privacy_patterns
    )
)

leakage_audit = pd.DataFrame(
    [
        {
            "check": "No future or label-derived score inputs",
            "matches": forbidden_score_overlap,
            "passed": len(forbidden_score_overlap) == 0,
        },
        {
            "check": "No future or label-derived queue fields",
            "matches": exported_forbidden_fields,
            "passed": len(exported_forbidden_fields) == 0,
        },
        {
            "check": "No privacy-risk queue fields",
            "matches": exported_privacy_risks,
            "passed": len(exported_privacy_risks) == 0,
        },
        {
            "check": "Identifiers are not score inputs",
            "matches": [],
            "passed": (
                "client_hash_id"
                not in score_input_columns
                and
                "content_hash_id"
                not in score_input_columns
            ),
        },
    ]
)

display(leakage_audit)

assert leakage_audit["passed"].all()


# ============================================================
# METRICS RECEIPT
# ============================================================

metrics_receipt = {
    "assignment": (
        "ML-07 Baseline Action Score and Top-20 Review"
    ),
    "lane": (
        "Refresh / Content Opportunity Scoring"
    ),
    "lane_locked": True,
    "development_month": "March 2026",
    "feature_window": (
        f"{FEATURE_START} to {FEATURE_END}"
    ),
    "outcome_window": (
        f"{OUTCOME_START} to {OUTCOME_END} "
        "for audit and evaluation only"
    ),
    "operational_rows": int(
        len(baseline_frame)
    ),
    "evaluation_rows": int(
        len(evaluation_frame)
    ),
    "queue_rows": int(
        len(ranked_queue)
    ),
    "reference_rows": int(
        len(reference_frame)
    ),
    "validation_rows": int(
        len(validation_frame)
    ),
    "reference_clients": int(
        len(reference_clients)
    ),
    "validation_clients": int(
        len(validation_clients)
    ),
    "client_overlap": int(
        client_overlap
    ),
    "validation_base_rate": (
        validation_base_rate
    ),
    "baseline_precision_at_50": (
        baseline_precision_at_50
    ),
    "top_50_positive_count": (
        top_50_positive_count
    ),
    "precision_lift_vs_base_rate": (
        precision_lift_vs_base_rate
    ),
    "minimum_impressions": MIN_IMPRESSIONS,
    "minimum_feature_days": MIN_FEATURE_DAYS,
    "score_weights": {
        "ctr_weakness": CTR_WEAKNESS_WEIGHT,
        "visibility_percentile": VISIBILITY_WEIGHT,
    },
    "reason_code": REASON_CODE,
    "action_label": ACTION_LABEL,
    "signal_verdicts": {
        "ctr_relative_to_position": signal_1_verdict,
        "visibility_impressions": signal_2_verdict,
    },
    "top_20_review_rows": int(
        len(top_20_review_output)
    ),
    "weak_picks_identified": int(
        len(weak_picks)
    ),
    "future_inputs_used_in_score": False,
    "label_derived_inputs_used_in_score": False,
    "identifier_features_used_in_score": False,
    "automatic_action": False,
    "causal_claim": False,
    "baseline_frozen_for_ml08": True,
}

with METRICS_PATH.open(
    "w",
    encoding="utf-8",
) as file:
    json.dump(
        metrics_receipt,
        file,
        indent=2,
    )

display(
    pd.DataFrame(
        [
            {
                "validation_base_rate": (
                    validation_base_rate
                ),
                "baseline_precision_at_50": (
                    baseline_precision_at_50
                ),
                "precision_lift_vs_base_rate": (
                    precision_lift_vs_base_rate
                ),
                "top_50_positive_count": (
                    top_50_positive_count
                ),
                "client_overlap": client_overlap,
                "queue_rows": len(ranked_queue),
            }
        ]
    ).round(4)
)

print("Saved:", METRICS_PATH)
print("Baseline frozen for ML-08.")

,rank,baseline_action_score,evidence_margin,weak_pick_reason
19,20,98.4621,0.94874,Rank 20 is relatively weaker because its combi...
18,19,98.5175,0.95058,Rank 19 is relatively weaker because its combi...
17,18,98.5228,0.95076,Rank 18 is relatively weaker because its combi...
16,17,98.6196,0.95399,Rank 17 is relatively weaker because its combi...
14,15,98.7191,0.95730,Rank 15 is relatively weaker because its combi...

                                     check matches  passed
0  No future or label-derived score inputs      []    True
1  No future or label-derived queue fields      []    True
2             No privacy-risk queue fields      []    True
3         Identifiers are not score inputs      []    True

,validation_base_rate,baseline_precision_at_50,precision_lift_vs_base_rate,top_50_positive_count,client_overlap,queue_rows
0,0.3008,0.52,0.2192,26,0,17038

Saved: work/outputs/baseline_metrics.json
Baseline frozen for ML-08.

## Results Summary

The baseline uses one transparent rule.

A page is queued when it is sufficiently visible, ranks between positions 1 and 20, and has CTR below the median for its position band.

The score uses:

- 70% position-adjusted CTR weakness;
- 30% visibility percentile.

Every queued page receives one reason code:

`visible_below_expected_ctr`

Every queued page receives one action label:

`review_title_meta_and_intent`

The grouped-client Precision@50 is reported next to the validation base rate.

The top 20 are reviewed manually with confidence notes and explicit conditions that could make each recommendation wrong.

The queue is intended for human decision-support. It does not prove that a page requires editing or that editing would cause recovery.

## Self-check

Before submission, this notebook confirms that:

- two signal checks include visible bucket tables and `n`;
- CTR relative to position is linked to a real FlyRank flag;
- both signals have valid one-word verdicts;
- the rule is written in plain words;
- score weights are fixed and hand-written;
- one reason code and one action label are used;
- `work/outputs/baseline_action_score.csv` is regenerated;
- Precision@50 is shown next to the validation base rate;
- grouped-client overlap is zero;
- all twenty review rows include action, reason, confidence, and failure condition;
- weak picks are identified;
- no future, label-derived, or product-decision input is used;
- IDs are grouping and joining keys only;
- no client names, URLs, or private queries appear;
- the baseline is frozen for ML-08;
- no automatic or causal claim is made.

In [10]:
allowed_verdicts = {
    "CONFIRMED",
    "OPPOSITE",
    "MIXED",
    "FALSE",
}

required_outputs = [
    QUEUE_PATH,
    METRICS_PATH,
]

self_checks = {
    "Exactly two signal checks": (
        len(signal_verdicts) == 2
    ),
    "Signal tables include n": (
        "n" in signal_1_table.columns
        and
        "n" in signal_2_table.columns
    ),
    "Flag-linked signal exists": bool(
        signal_verdicts.loc[
            signal_verdicts["signal"].eq(
                "CTR relative to position"
            ),
            "flag_linked",
        ].iloc[0]
    ),
    "Both verdicts are valid": (
        signal_1_verdict in allowed_verdicts
        and
        signal_2_verdict in allowed_verdicts
    ),
    "CTR signal is confirmed": (
        signal_1_verdict == "CONFIRMED"
    ),
    "Rule weights sum to one": np.isclose(
        CTR_WEAKNESS_WEIGHT
        + VISIBILITY_WEIGHT,
        1.0,
    ),
    "Operational frame is feature-only": (
        "outcome_impressions"
        not in baseline_frame.columns
        and
        "outcome_available_days"
        not in baseline_frame.columns
        and
        "is_declining_proxy"
        not in baseline_frame.columns
    ),
    "Queue is non-empty": (
        len(ranked_queue) > 0
    ),
    "Queue ranks are sequential": (
        ranked_queue["rank"].tolist()
        ==
        list(
            range(
                1,
                len(ranked_queue) + 1,
            )
        )
    ),
    "Exactly one reason code": (
        ranked_queue["reason_code"].nunique() == 1
        and
        ranked_queue["reason_code"].iloc[0]
        == REASON_CODE
    ),
    "Exactly one action label": (
        ranked_queue["action_label"].nunique() == 1
        and
        ranked_queue["action_label"].iloc[0]
        == ACTION_LABEL
    ),
    "All queue rows satisfy CTR rule": (
        ranked_queue["ctr_gap"].lt(0).all()
    ),
    "Scores are finite": np.isfinite(
        ranked_queue["baseline_action_score"]
    ).all(),
    "Validation base rate is valid": (
        0 <= validation_base_rate <= 1
    ),
    "Precision at 50 is valid": (
        0 <= baseline_precision_at_50 <= 1
    ),
    "Client overlap is zero": (
        client_overlap == 0
    ),
    "Twenty review rows exist": (
        len(top_20_review_output)
        == TOP_REVIEW_N
    ),
    "Top-20 requirements are populated": all(
        top_20_review_output[column]
        .astype(str)
        .str.len()
        .gt(0)
        .all()
        for column in [
            "action_label",
            "reason_code",
            "confidence_note",
            "what_would_make_it_wrong",
            "review_line",
        ]
    ),
    "Weak picks identified": (
        len(weak_picks) >= 1
    ),
    "Leakage audit passes": (
        leakage_audit["passed"].all()
    ),
    "Baseline is frozen": (
        metrics_receipt[
            "baseline_frozen_for_ml08"
        ] is True
    ),
    "No automatic action": (
        metrics_receipt[
            "automatic_action"
        ] is False
    ),
    "No causal claim": (
        metrics_receipt[
            "causal_claim"
        ] is False
    ),
    "Required outputs exist": all(
        path.exists()
        for path in required_outputs
    ),
}

self_check_df = pd.DataFrame(
    {
        "check": list(self_checks.keys()),
        "passed": list(self_checks.values()),
    }
)

display(self_check_df)

failed_checks = [
    check_name
    for check_name, passed
    in self_checks.items()
    if not passed
]

if failed_checks:
    raise AssertionError(
        "ML-07 self-check failed: "
        + ", ".join(failed_checks)
    )

print("All ML-07 self-checks passed.")

                                check  passed
0           Exactly two signal checks    True
1             Signal tables include n    True
2           Flag-linked signal exists    True
3             Both verdicts are valid    True
4             CTR signal is confirmed    True
5             Rule weights sum to one    True
6   Operational frame is feature-only    True
7                  Queue is non-empty    True
8          Queue ranks are sequential    True
9             Exactly one reason code    True
10           Exactly one action label    True
11    All queue rows satisfy CTR rule    True
12                  Scores are finite    True
13      Validation base rate is valid    True
14           Precision at 50 is valid    True
15             Client overlap is zero    True
16           Twenty review rows exist    True
17  Top-20 requirements are populated    True
18              Weak picks identified    True
19               Leakage audit passes    True
20                 Baseline is frozen    True
21                No automatic action    True
22                    No causal claim    True
23             Required outputs exist    True

All ML-07 self-checks passed.